;*****************************************************
; APPMENU PANEL INI
;*****************************************************

[global]
version = 1.0               ; INIfile version

[theme]
backgroundcolor = #1e1e1e
color = #ffffff

